### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by ad3154** [cmake-lint/cmake-lint#17]
Admittedly, I'm very much not a "python guy" so I am not sure what to make of this, but the output asked to consider creating an issue here!

```
~/$ cmake-lint --config=.cmakelintrc CMakeLists.txt
ERROR An internal error occured. Please consider filing a bug report at github.com/cheshirekow/cmakelang/issues
Traceback (most recent call last):
  File "/home/arcangel/.local/lib/python3.8/site-packages/cmakelang/lint/__main__.py", line 185, in main
    return inner_main()
  File "/home/arcangel/.local/lib/python3.8/site-packages/cmakelang/lint/__main__.py", line 143, in inner_main
    config_dict = __main__.get_config(infile_path, args.config_files)
  File "/home/arcangel/.local/lib/python3.8/site-packages/cmakelang/format/__main__.py", line 359, in get_config
    return get_configdict(configfile_paths)
  File "/home/arcangel/.local/lib/python3.8/site-packages/cmakelang/format/__main__.py", line 314, in get_configdict
    for include_path in increment_dict.pop("include", []):
AttributeError: 'str' object has no attribute 'pop'
```

The file content of .cmakelintrc are
```
filter=-linelength
<newline>
```

Where `<newline>` is a blank line

**Comment by tkruse** [comment]
thanks for reporting this, we can keep the issue open until someone (like me) has time to fix this
