### ISSUE TITLE
Unable to install in Python 3.12

### ISSUE THREAD

**Issue by SigureMo** [cmake-lint/cmake-lint#25]
When I try to install cmake-lint in Python 3.12, it reports the following error:

```
> pip install .              
Processing /Users/nyakku/Projects/cmake-lint
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/nyakku/Projects/cmake-lint/setup.py", line 3, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

This is because Python 3.12 has removed `imp` and recommends using `importlib` instead[^1].

[^1]: https://docs.python.org/3.12/whatsnew/3.12.html#imp

**Comment by Freed-Wu** [comment]
Can 1.4.3 be published to support python 3.12?

**Comment by StStME** [comment]
Hi @Freed-Wu,
I will aim for that next week.

**Comment by StStME** [comment]
HI @Freed-Wu 
1.4.3 is now available on pypi!
